# Generated by Django 5.1.7 on 2025-03-31 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzamodel',
            old_name='ingredientes',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='pizzamodel',
            old_name='name',
            new_name='nome',
        ),
    ]
